// leave off @2x/@3x
const images = {
  2: require('../Images/2.png'),
  bg: require('../Images/BG.png'),
  cheddrBelowGreen: require('../Images/Cheddr-BELOW-Green.png'),
  cheddrSideBlack: require('../Images/Cheddr-SIDE-Black.png'),
  cheddrSideGray: require('../Images/Cheddr-SIDE-Gray.png'),
  cheddrheader: require('../Images/CheddrHeader.png'),
  gear: require('../Images/Gear.png'),
  geoTargeted: require('../Images/Geo-targeted.png'),
  cheddrIcon: require('../Images/cheddr-icon.png'),
  cheddrProduct: require('../Images/cheddr-product.png'),
  cheddrcharcoal: require('../Images/cheddrCharcoal.png'),
  cheddrgreen: require('../Images/cheddrGreen.png'),
  cheddrwhite: require('../Images/cheddrWhite.png'),
  download: require('../Images/download.png'),
  gearwithoval: require('../Images/gearWithOval.png'),
  hopriver: require('../Images/hopRiver.png'),
  icNearMe48pt3x: require('../Images/ic_near_me_48pt_3x.png'),
  icecase: require('../Images/iceCase.png'),
  igniteLogo: require('../Images/ignite_logo.png'),
  ir: require('../Images/ir.png'),
  logonoshadow: require('../Images/logoNoShadow.png'),
  logonotext: require('../Images/logoNoText.png'),
  mountTaishan2: require('../Images/mount-taishan-2.png'),
  nearmeoriginal: require('../Images/nearMeOriginal.png'),
  nearbyCheddr: require('../Images/nearby-cheddr.png'),
  nearme: require('../Images/nearme.png'),
  noahswater: require('../Images/noahsWater.png'),
  piechart: require('../Images/pieChart.png'),
  product: require('../Images/product.png'),
  profile: require('../Images/profile.png'),
  someBlackGuy: require('../Images/some-black-guy.png'),
  sparklingicebox: require('../Images/sparklingiceBox.png'),
  statsIcon: require('../Images/stats-icon.png'),
  statswithoval: require('../Images/statsWithOval.png'),
  stoneipa: require('../Images/stoneIpa.png'),
  tileBg: require('../Images/tile_bg.png'),
  topLogo: require('../Images/top_logo.png'),
  vitacoco: require('../Images/vitaCoco.png'),
  bg: require('../Images/BG.png'),
  cheddrSideBlack: require('../Images/Cheddr-SIDE-Black.png'),
  cheddrSideGray: require('../Images/Cheddr-SIDE-Gray.png'),
  cheddrcharcoal: require('../Images/cheddrCharcoal.png'),
  cheddrgreen: require('../Images/cheddrGreen.png'),
  cheddrwhite: require('../Images/cheddrWhite.png'),
  icNearMe48pt3x: require('../Images/ic_near_me_48pt_3x.png'),
  icecase: require('../Images/iceCase.png'),
  igniteLogo: require('../Images/ignite_logo.png'),
  ir: require('../Images/ir.png'),
  logonotext: require('../Images/logoNoText.png'),
  mountTaishan2: require('../Images/mount-taishan-2.png'),
  nearmeoriginal: require('../Images/nearMeOriginal.png'),
  nearme: require('../Images/nearme.png'),
  sparklingicebox: require('../Images/sparklingiceBox.png'),
  tileBg: require('../Images/tile_bg.png'),
  topLogo: require('../Images/top_logo.png'),

}

export default images
